tools_dir: /home/build/tools
downloads_dir: /home/build/downloads
openshift_config_dir: /var/lib/origin/openshift.local.config
openshift_node_config_file: "{{ openshift_config_dir }}/node-localhost/node-config.yaml"
openshift_version: 3.11.0
openshift_hash: 0cbc58b
openshift_tag: v3.11
debezium_tag: 0.8
strimzi_tag: 0.8.0
prometheus_tag: v2.4.0
elasticsearch_tag: 6.4.2
