- name: set-up build environment
  become: yes
  become_user: build
  block:

    - name: Have {{ tools_dir }}
      file: path={{ tools_dir }} state=directory
    - name: Have {{ downloads_dir }}
      file: path={{ downloads_dir }} state=directory
    - name: Have {{ jdks_dir }}
      file: path={{ jdks_dir }} state=directory
    - name: Have /home/build/.m2
      file: path=/home/build/.m2 state=directory

    - name: Have Maven {{ maven_version }}
      get_url:
        url: https://dlcdn.apache.org/maven/maven-3/{{ maven_version }}/binaries/apache-maven-{{ maven_version }}-bin.tar.gz
        dest: "{{ downloads_dir }}"
    - name: Have Maven {{ maven_version }} unpacked
      unarchive:
        src: "{{ downloads_dir }}/apache-maven-{{ maven_version }}-bin.tar.gz"
        dest: "{{ tools_dir }}"
        remote_src: True
        creates: "{{ tools_dir }}/apache-maven-{{ maven_version }}"

    - name: Have Java 18
      get_url:
        url: https://download.java.net/java/GA/jdk18.0.1.1/65ae32619e2f40f3a9af3af1851d6e19/2/GPL/openjdk-18.0.1.1_linux-x64_bin.tar.gz
        dest: "{{ downloads_dir }}/openjdk-18.0.1.1_linux-x64_bin.tar.gz"
    - name: Have Java 18 unpacked
      unarchive:
        src: "{{ downloads_dir }}/openjdk-18.0.1.1_linux-x64_bin.tar.gz"
        dest: "{{ jdks_dir }}"
        remote_src: True
        creates: "{{ jdks_dir }}/jdk-18.0.1.1"

    - name: Have Java 19
      get_url:
        url: https://download.java.net/java/GA/jdk19.0.1/afdd2e245b014143b62ccb916125e3ce/10/GPL/openjdk-19.0.1_linux-x64_bin.tar.gz
        dest: "{{ downloads_dir }}/openjdk-19.0.1_linux-x64_bin.tar.gz"
    - name: Have Java 19 unpacked
      unarchive:
        src: "{{ downloads_dir }}/openjdk-19.0.1_linux-x64_bin.tar.gz"
        dest: "{{ jdks_dir }}"
        remote_src: True
        creates: "{{ jdks_dir }}/jdk-19.0.1"

    - name: Have toolchains.xml
      copy:
        src: toolchains.xml
        dest: /home/build/.m2/toolchains.xml
        mode: 0600
    - name: Have settings.xml
      copy:
        src: settings.xml
        dest: /home/build/.m2/settings.xml
        mode: 0600

    # run this to switch JDK versions: sudo alternatives --config java_home
    # run this to install further alternative versions:
    # sudo update-alternatives --install /usr/lib/jvm/java_home java_home /home/build/jdks/jdk-19 1
    - name: set-up alternatives
      become: yes
      become_user: root
      block:
        - name: Have /usr/lib/jvm
          file: path=/usr/lib/jvm state=directory
        - name: Have Maven as alternative
          alternatives:
            name: mvn
            link: /usr/bin/mvn
            path: "{{ tools_dir }}/apache-maven-{{ maven_version }}/bin/mvn"
        - name: Have mvnDebug as alternative
          alternatives:
            name: mvnDebug
            link: /usr/bin/mvnDebug
            path: "{{ tools_dir }}/apache-maven-{{ maven_version }}/bin/mvnDebug"

        - name: Have Java 18 as alternative
          alternatives:
            name: java_home
            link: /usr/lib/jvm/java_home
            path: "{{ jdks_dir }}/jdk-18.0.1.1"
        - name: Have Java 19 as alternative
          alternatives:
            name: java_home
            link: /usr/lib/jvm/java_home
            path: "{{ jdks_dir }}/jdk-19.0.1"
