- name: set-up build environment
  become: yes
  become_user: build
  block:

    - name: Have {{ tools_dir }}
      file: path={{ tools_dir }} state=directory
    - name: Have {{ downloads_dir }}
      file: path={{ downloads_dir }} state=directory
    - name: Have {{ jdks_dir }}
      file: path={{ jdks_dir }} state=directory
    - name: Have /home/build/.m2
      file: path=/home/build/.m2 state=directory

    - name: Have Maven {{ maven_version }}
      get_url:
        url: http://mirror.netcologne.de/apache.org/maven/maven-3/{{ maven_version }}/binaries/apache-maven-{{ maven_version }}-bin.tar.gz
        dest: "{{ downloads_dir }}"
    - name: Have Maven {{ maven_version }} unpacked
      unarchive:
        src: "{{ downloads_dir }}/apache-maven-{{ maven_version }}-bin.tar.gz"
        dest: "{{ tools_dir }}"
        remote_src: True
        creates: "{{ tools_dir }}/apache-maven-{{ maven_version }}"

    - name: Have Java 11
      get_url:
        url: https://github.com/AdoptOpenJDK/openjdk11-upstream-binaries/releases/download/jdk-{{ jdk_lts }}%2B{{ jdk_lts_build }}/OpenJDK11U-jdk_x64_linux_{{ jdk_lts }}_{{ jdk_lts_build }}.tar.gz
        dest: "{{ downloads_dir }}/OpenJDK11U-jdk_x64_linux_{{ jdk_lts }}_{{ jdk_lts_build }}.tar.gz"
    - name: Have Java 11 unpacked
      unarchive:
        src: "{{ downloads_dir }}/OpenJDK11U-jdk_x64_linux_{{ jdk_lts }}_{{ jdk_lts_build }}.tar.gz"
        dest: "{{ jdks_dir }}"
        remote_src: True
        creates: "{{ jdks_dir }}/openjdk-{{ jdk_lts }}+{{ jdk_lts_build }}"

    - name: Have Java 16
      get_url:
        url: https://download.java.net/java/GA/jdk16.0.2/d4a915d82b4c4fbb9bde534da945d746/7/GPL/openjdk-16.0.2_linux-x64_bin.tar.gz
        dest: "{{ downloads_dir }}/openjdk-16-ea+34_linux-x64_bin.tar.gz"
    - name: Have Java 16 unpacked
      unarchive:
        src: "{{ downloads_dir }}/openjdk-16-ea+34_linux-x64_bin.tar.gz"
        dest: "{{ jdks_dir }}"
        remote_src: True
        creates: "{{ jdks_dir }}/jdk-16"

    - name: Have toolchains.xml
      copy:
        src: toolchains.xml
        dest: /home/build/.m2/toolchains.xml
        mode: 0600
    - name: Have settings.xml
      copy:
        src: settings.xml
        dest: /home/build/.m2/settings.xml
        mode: 0600

    # run this to switch JDK versions: sudo alternatives --config java_home
    - name: set-up alternatives
      become: yes
      become_user: root
      block:
        - name: Have /usr/lib/jvm
          file: path=/usr/lib/jvm state=directory
        - name: Have Maven as alternative
          alternatives:
            name: mvn
            link: /usr/bin/mvn
            path: "{{ tools_dir }}/apache-maven-{{ maven_version }}/bin/mvn"
        - name: Have mvnDebug as alternative
          alternatives:
            name: mvnDebug
            link: /usr/bin/mvnDebug
            path: "{{ tools_dir }}/apache-maven-{{ maven_version }}/bin/mvnDebug"

        - name: Have Java 11 as alternative
          alternatives:
            name: java_home
            link: /usr/lib/jvm/java_home
            path: "{{ jdks_dir }}/openjdk-{{ jdk_lts }}_{{ jdk_lts_build }}"
        - name: Have Java 16 as alternative
          alternatives:
            name: java_home
            link: /usr/lib/jvm/java_home
            path: "{{ jdks_dir }}/jdk-16.0.2"
