- name: Have docker repo
  shell:  'dnf config-manager \
    --add-repo \
    https://download.docker.com/linux/fedora/docker-ce.repo'
- name: Have dnf cache updated
  shell: 'dnf makecache'

# sudo dnf config-manager     --add-repo     https://download.docker.com/linux/fedora/docker-ce.repo
# sudo dnf config-manager --set-enabled docker-ce-test
# sudo dnf install docker-ce docker-ce-cli containerd.io
# sudo systemctl start docker
# sudo systemctl enable docker

# sudo usermod -aG docker $USER
# logout, login
# docker run --rm -p 80 -d nginx
# curl localhost

- name: Have Docker
  dnf: name={{item}} state=latest
  with_items:
    - docker-ce
    - docker-ce-cli
    - containerd.io
- name: add docker group
  group: name=docker state=present
- name: Have /etc/docker
  file: path=/etc/docker state=directory
- name: Have daemon.json
  copy:
    src: docker_daemon.json
    dest: /etc/docker/daemon.json

- name: Ensure Docker is started
  systemd:
    state: started
    enabled: yes
    name: docker

- name: add user
  user: name=build groups=docker state=present append=yes
