- name: upgrade all packages
  dnf: name="*" state=latest
- name: Have common tools
  dnf: name={{item}} state=latest
  with_items:
     - git
     - wget
     - the_silver_searcher
     - htop
     - acl
     - dnf-plugins-core
     - bash-completion
     - libselinux-python
     - jq
     - gnupg
     # run sudo haveged --run=0 to fill entropy pool for key generation
     - haveged
     - vim-enhanced
     - entr
     # - java-1.8.0-openjdk-devel

- name: have build user
  user:
    name: build
    shell: /bin/bash

- name: add wheel group
  group:
    name: wheel
    state: present
- name: Allow wheel group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    validate: visudo -cf %s

- name: add user
  user: name=build groups=wheel state=present append=yes

- name: Have .bashrc
  become: yes
  become_user: build
  copy:
    src: user_bashrc
    dest: /home/build/.bashrc
    mode: 0644
