- name: upgrade all packages
  become: true
  become_user: root
  dnf: name="*" state=latest
- name: Have common tools
  become: true
  become_user: root
  dnf: name={{item}} state=latest
  with_items:
     - git
     - wget
     - the_silver_searcher
     - htop
     - acl
     - dnf-plugins-core
     - bash-completion
     - jq
     - gnupg
     # run sudo haveged --run=0 to fill entropy pool for key generation
     - haveged
     - vim-enhanced
     - entr
     - zip
     - fail2ban

- name: Have .bashrc
  copy:
    src: user_bashrc
    dest: /home/{{ user }}/.bashrc
    mode: 0644
